/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { PayMasterABI } from "@/abi/PayMaster";
import { PropertyTokenABI } from "@/abi/PropertyToken";
import { RentToOwnABI } from "@/abi/RentToOwn";
import { GenericContractsDeclaration } from "@/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    RentToOwnContract: {
      address: "",
      abi: RentToOwnABI,
      inheritedFunctions: {},
    },
    PayMasterContract: {
      address: "",
      abi: PayMasterABI,
      inheritedFunctions: {},
    },
    PropertyTokenContract: {
      address: "",
      abi: PropertyTokenABI,
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
